# -*- coding: utf-8 -*-
"""Position Salary .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OZ0qppKX3DAJ-_RpIIsREEsDALAxHdZU
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

path = '/content/Position_Salaries.csv'
df = pd.read_csv(path)
df

X = df.iloc[:, 1:-1].values
y = df.iloc[:, -1].values

plt.scatter(X, y)
plt.title('Salary vs Position Data')
plt.xlabel('Level')
plt.ylabel('Salary')
plt.show()

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X, y)

plt.scatter(X, y, color='red')
plt.plot(X, lr.predict(X), color='blue')
plt.title('Salary vs Position Data')
plt.xlabel('Level')
plt.ylabel('Salary')
plt.show()

from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X)
lr_2 = LinearRegression()
lr_2.fit(X_poly, y)

plt.scatter(X, y, color = 'red')
plt.plot(X, lr_2.predict(poly_reg.fit_transform(X)), color = 'blue')
plt.title('Truth or Bluff (Polynomial Regression)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()